### ISSUE TITLE
Alter diasUteis()

### ISSUE THREAD

**Issue by gmuraoka** [gabrielsolucoesvip/gabrielsolucoesvip.github.io#6]
Change day gap from start to end of processing.
`i` must be 0 and also needs a counter, point where processing must stop:

    var c;
    if(isFinanceiro == true){
        c = arrDias.length -1;
    }
    else{
        c = arrDias.length;
    }
and `for` loop must use `c` as iterator:
`for(i; i < c;i++){`

**Comment by gabrielsolucoesvip** [comment]
Done
